create extension if not exists btree_gist;

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  first_name text not null check (length(trim(first_name)) > 0),
  last_name text not null check (length(trim(last_name)) > 0)
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  first_name text not null check (length(trim(first_name)) > 0),
  last_name text not null check (length(trim(last_name)) > 0)
);

create table if not exists public.interventions (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete restrict,
  employee_id bigint not null references public.employees(id) on delete restrict,
  start_at timestamp without time zone not null,
  end_at timestamp without time zone not null,
  constraint interventions_valid_period check (end_at > start_at),
  constraint interventions_employee_no_overlap exclude using gist
    (employee_id with =, tsrange(start_at, end_at, '[)') with &&)
);

create index if not exists interventions_start_at_idx on public.interventions(start_at);
create index if not exists interventions_client_id_idx on public.interventions(client_id);

alter table public.clients enable row level security;
alter table public.employees enable row level security;
alter table public.interventions enable row level security;
